Provide a basic configuration block
mirumee/ariadne-codegen pull request #139
Opened 2023-04-28 05:54 UTC by jensenbox

This is to make it dirt simple for someone to get started. This makes it easy to copy past and get started a smidge faster than copy/pasting each element that they may need.

2023-04-28 16:38 UTC, rafalp requested changes

2023-04-28 16:38 UTC, rafalp commented on README.md
> +Example minimum onfiguration block:
```suggestion
Minimal configuration for client generation:

```

2023-04-28 16:38 UTC, rafalp commented on README.md
> +queries_path="queries.graphql"
```suggestion
queries_path = "queries.graphql"
```

2023-04-28 19:59 UTC, jensenbox reviewed
Changes accepted.

2023-05-08 09:52 UTC, mat-sop approved these changes

2023-05-08 10:43 UTC, merged