Add/keep python3.8 support (dict -> Dict) for generated code
mirumee/ariadne-codegen pull request #188
Opened 2023-07-24 13:38 UTC by gst

Fix: https://github.com/mirumee/ariadne-codegen/issues/187

2023-07-27 09:09 UTC, mat-sop requested changes

2023-07-27 09:09 UTC, mat-sop commented on ariadne_codegen/client_generators/client.py
> +                generate_name("Dict"),
We should use the constant as well
```suggestion
                generate_name(DICT),
```

2023-07-27 09:09 UTC, mat-sop commented on tests/client_generators/test_client_generator.py
> +                value=ast.Name(id="Dict"),
```suggestion
                value=ast.Name(id=DICT),
```

2023-07-27 09:09 UTC, mat-sop commented on tests/client_generators/test_client_generator.py
> +                value=ast.Name(id="Dict"),
```suggestion
                value=ast.Name(id=DICT),
```

2023-07-27 09:09 UTC, mat-sop commented on tests/client_generators/test_client_generator.py
> +                    value=ast.Name(id="Dict"),
```suggestion
                    value=ast.Name(id=DICT),
```

2023-07-27 09:09 UTC, mat-sop commented on ariadne_codegen/graphql_schema_generators/utils.py
> +            generate_name(_keep_dict_tuple_capitalized(type_)),
Hmm, I don't see a point in this change. `type_` has the annotation `GraphQLNamedType`, so it shouldn't get `dict` or `tuple`. Am I missing something? Do you see a case where it's necessary?

2023-07-27 16:01 UTC, gst commented
hmm @mat-sop 

ideally this would not deserve a python3.8 build/CI (run) test configuration too ?

2023-07-28 08:15 UTC, mat-sop approved these changes

2023-07-28 08:26 UTC, mat-sop commented
> hmm @mat-sop
> 
> ideally this would not deserve a python3.8 build/CI (run) test configuration too ?

Ideally yes, but most of our tests check if the generated package looks like expected and we can't run those tests on `3.8`
To include `3.8` in our ci we would need to:
1. Use separate python versions for generation and client tests.
2. Create tests that check only the behavior of the generated client.

`1.` seems relatively easy to do, but `2.` definitely requires more work, so it may be something to consider in the future. Of course, if you want to create those tests, contributions are very welcome 😄

2023-07-28 14:48 UTC, gst commented
> Use separate python versions for generation and client tests.

yes obviously :)

> Create tests that check only the behavior of the generated client.

that would be out of the scope of this PR ;)

but you could have simple checks, kind of : 

1) import every generated sub-module, must succeed, obviously.
2) egrep "[^\w](dict|tuple)\[" **/*.py ; for not top-level annotations.

eventually.

2023-08-02 10:42 UTC, rafalp approved these changes
LGTM. We'll need to remember to mention this change in changelog after this is merged.

2023-08-02 12:57 UTC, merged