Add opentelemetry to base clients
mirumee/ariadne-codegen pull request #227
Opened 2023-10-06 11:20 UTC by mat-sop

This pr adds opentelemetry to both base clients

resolves #200

2023-10-06 11:28 UTC, rafalp commented
I am wondering if this code should only be included if feature flag is enabled 🤔 But that would explode the complexity by a lot?

2023-10-06 11:36 UTC, mat-sop commented
> I am wondering if this code should only be included if feature flag is enabled 🤔 But that would explode the complexity by a lot?

Hmm, we could treat them as separate base clients, e.g. `BaseClient`, `AsyncBaseClient`, `BaseClientWithTelemetry`, `AsyncBaseClientWithTelemetry` and decide which one to use based on 2 options - `async_client` (already exists) and something like `include_telemetry`.

This wouldn't add much complexity as we already have the option to provide a fully custom base client, it's only a matter of providing a path to a different file.

2023-10-09 15:28 UTC, rafalp requested changes
Let's keep base clients base, and introduce separate clients for telemetry.

2023-10-11 09:29 UTC, rafalp requested changes
"Telemetry" is unspecific in world of APM solutions, so we should use `opentelemetry` instead of `telemetry` for variable/option/class names.

For example `BaseClientOpenTelemetry` would be more descriptive than `BaseClientWithTelemetry`.

I understand some names will java'squely long, but their meaning would save us confusion in future.

2023-10-11 09:29 UTC, rafalp commented on CHANGELOG.md
> +- Added additional base clients with opentelemetry support. Added `telemetry_client` config option.
```suggestion
- Added additional base clients supporting the Open Telemetry tracing. Added `opentelemetry_client` config option.
```

2023-10-11 09:29 UTC, rafalp commented on README.md
> +### Opentelemetry
```suggestion
### Open Telemetry
```

2023-10-11 09:29 UTC, rafalp commented on README.md
> +- `telemetry_client` (defaults to `false`) - default base clients doesn't support opentelemetry, change this option to `true` to use base client with opentelemetry
```suggestion
- `opentelemetry_client` (defaults to `false`) - default base clients don't support any performance tracing. Change this option to `true` to use the base client with Open Telemetry support.
```

2023-10-11 09:29 UTC, rafalp commented on README.md
> +When config option `telemetry_client` is set to `true` then default, included base clients support opt-in telemetry options. By default, it's disabled, but when the `opentelemetry-api` package is ins
```suggestion
When config option `opentelemetry_client` is set to `true` then default, included base client is replaced with one that implements the opt-in Open Telemetry support. By default this support does nothing but when the `opentelemetry-api` package is installed and the `tracer` argument is provided then the client will create spans with data about performed requests.
```

2023-10-11 09:29 UTC, rafalp commented on .github/workflows/tests.yml
> +        pip install -e .[subscriptions,telemetry,dev]
```suggestion
        pip install -e .[subscriptions,opentelemetry,dev]
```

2023-10-11 12:27 UTC, rafalp approved these changes

2023-10-11 12:27 UTC, rafalp commented on README.md
> +Telemetry arguments handled by `BaseClientOpenTelemetry`:
```suggestion
Tracing arguments handled by `BaseClientOpenTelemetry`:
```

2023-10-11 12:50 UTC, merged