fix: Argument type only uses scalar and ignore list
mirumee/ariadne-codegen pull request #327
Opened 2024-11-15 01:30 UTC by flonou

This should fix #321 
I'm not completely sure all GraphQL Types are correctly handled

I will check if I can provide tests for this if needed

2025-03-30 02:25 UTC, normanre requested changes
Hi,
i think you put up a neat solution. It seems like you did not get to run you code, because there would be a syntax error.

I commented a solution in the line with the error.

Furthermore, a similar problem which is fixed #347 is also missing here.

2025-03-30 02:25 UTC, normanre commented on ariadne_codegen/client_generators/custom_arguments.py
> +        constant_value = self._generate_complete_type_name(complete_type)
this would cause a syntax error. the variable `complete_type` does not seem to be defined. I think you can drop the parameter `final_type` and put your new parameter `complete_type` there, then in `generate_arguments()` you pass `complete_type=arg_value.type` to `_accumulate_return_arguments()`.

2025-03-30 10:06 UTC, flonou commented on ariadne_codegen/client_generators/custom_arguments.py
> +        constant_value = self._generate_complete_type_name(complete_type)
Indeed I must have messed up with my git client. My local code is exactly what you describe. I'll push a new commit

2025-09-22 11:53 UTC, DamianCzajkowski commented
Fixed in https://github.com/mirumee/ariadne-codegen/pull/363

2025-09-22 11:53 UTC, closed without merging